// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type NetworkInitParameters struct {

	// Additional IPs to be assigned
	// to this server.
	AliasIps []*string `json:"aliasIps,omitempty" tf:"alias_ips,omitempty"`

	// IP to request to be assigned to this server.
	// If you do not provide this then you will be auto assigned an IP
	// address.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// ID of the network which should be added
	// to the server. Required if subnet_id is not set. Successful creation
	// of the resource depends on the existence of a subnet in the Hetzner
	// Cloud Backend. Using network_id will not create an explicit
	// dependency between server and subnet. Therefore depends_on may need
	// to be used. Alternatively the subnet_id property can be used, which
	// will create an explicit dependency between hcloud_server_network and
	// the existence of a subnet.
	NetworkID *float64 `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// ID of the server.
	ServerID *float64 `json:"serverId,omitempty" tf:"server_id,omitempty"`

	// ID of the sub-network which should be
	// added to the Server. Required if network_id is not set.
	// Note: if the ip property is missing, the Server is currently added
	// to the last created subnet.
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`
}

type NetworkObservation struct {

	// Additional IPs to be assigned
	// to this server.
	AliasIps []*string `json:"aliasIps,omitempty" tf:"alias_ips,omitempty"`

	// (string) ID of the server network.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IP to request to be assigned to this server.
	// If you do not provide this then you will be auto assigned an IP
	// address.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// ID of the network which should be added
	// to the server. Required if subnet_id is not set. Successful creation
	// of the resource depends on the existence of a subnet in the Hetzner
	// Cloud Backend. Using network_id will not create an explicit
	// dependency between server and subnet. Therefore depends_on may need
	// to be used. Alternatively the subnet_id property can be used, which
	// will create an explicit dependency between hcloud_server_network and
	// the existence of a subnet.
	NetworkID *float64 `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// ID of the server.
	ServerID *float64 `json:"serverId,omitempty" tf:"server_id,omitempty"`

	// ID of the sub-network which should be
	// added to the Server. Required if network_id is not set.
	// Note: if the ip property is missing, the Server is currently added
	// to the last created subnet.
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`
}

type NetworkParameters struct {

	// Additional IPs to be assigned
	// to this server.
	// +kubebuilder:validation:Optional
	AliasIps []*string `json:"aliasIps,omitempty" tf:"alias_ips,omitempty"`

	// IP to request to be assigned to this server.
	// If you do not provide this then you will be auto assigned an IP
	// address.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// ID of the network which should be added
	// to the server. Required if subnet_id is not set. Successful creation
	// of the resource depends on the existence of a subnet in the Hetzner
	// Cloud Backend. Using network_id will not create an explicit
	// dependency between server and subnet. Therefore depends_on may need
	// to be used. Alternatively the subnet_id property can be used, which
	// will create an explicit dependency between hcloud_server_network and
	// the existence of a subnet.
	// +kubebuilder:validation:Optional
	NetworkID *float64 `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// ID of the server.
	// +kubebuilder:validation:Optional
	ServerID *float64 `json:"serverId,omitempty" tf:"server_id,omitempty"`

	// ID of the sub-network which should be
	// added to the Server. Required if network_id is not set.
	// Note: if the ip property is missing, the Server is currently added
	// to the last created subnet.
	// +kubebuilder:validation:Optional
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`
}

// NetworkSpec defines the desired state of Network
type NetworkSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NetworkParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkInitParameters `json:"initProvider,omitempty"`
}

// NetworkStatus defines the observed state of Network.
type NetworkStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NetworkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Network is the Schema for the Networks API. Provides a Hetzner Cloud Server Network to represent a private network on a server in the Hetzner Cloud.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,hcloud}
type Network struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serverId) || (has(self.initProvider) && has(self.initProvider.serverId))",message="spec.forProvider.serverId is a required parameter"
	Spec   NetworkSpec   `json:"spec"`
	Status NetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkList contains a list of Networks
type NetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Network `json:"items"`
}

// Repository type metadata.
var (
	Network_Kind             = "Network"
	Network_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Network_Kind}.String()
	Network_KindAPIVersion   = Network_Kind + "." + CRDGroupVersion.String()
	Network_GroupVersionKind = CRDGroupVersion.WithKind(Network_Kind)
)

func init() {
	SchemeBuilder.Register(&Network{}, &NetworkList{})
}
